name: Speedtest

on:
    push:
        branches:
            - main
    workflow_dispatch:
    
permissions:
  contents: write
  deployments: write
jobs:
    Speedtest:
        runs-on: ubuntu-latest
        steps: 
            - name: 安装依赖
              run: |
                sudo apt-get install curl
                curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
                sudo apt-get install speedtest
            
            - name: 检出仓库
              uses: actions/checkout@v4

            - name: 速度测试
              run: |
                speedtest --accept-license > Speedtest.txt

            - name: 获取内容
              id: speedtest_result
              run: |
                  CONTENT=$(< Speedtest.txt) # 直接读取文件内容
                  echo "SPEEDTEST_RESULT<<EOF" >> $GITHUB_ENV
                  echo "$CONTENT" >> $GITHUB_ENV
                  echo "EOF" >> $GITHUB_ENV
            
            
            - name: 设置动态标签
              id: set_tag
              run: echo "TAG_NAME=Speedtest-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

            - name: 发布 Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ env.TAG_NAME }}
                release_name: '[Speedtest] 速度测试'
                body: ${{ env.SPEEDTEST_RESULT }}
                draft: false
                prerelease: false

            - name: 上传 Assests
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: Speedtest.txt  # 替换为你的资产路径
                asset_name: Speedtest - $(date +'%Y.%m.%d.%H.%M.%S').txt  # 替换为你的资产文件名
                asset_content_type: txt  # 根据你的资产类型修改