name: Speedtest

on:
    workflow_dispatch:

jobs:
    Speedtest:
        runs-on: ubuntu-latest
        steps: 
            - name: 安装依赖
              run: |
                sudo apt-get install curl
                curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
                sudo apt-get install speedtest
            
            - name: 检出仓库
              uses: actions/checkout@v4

            - name: 速度测试
              run: |
                speedtest --accept-license > Speedtest.txt

            - name: 获取内容
              id: speedtest_result
              run: |
                CONTENT=$(cat Speedtest.txt | xargs) # 去掉多余的空格
                echo "SPEEDTEST_RESULT=${CONTENT//[$'\n']/ }" >> $GITHUB_ENV # 将换行符替换为空格
            
            - name: 发布 Release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
              with:
                tag_name: 'Speedtest'
                release_name: '[Speedtest] 速度测试'
                body: ${{ env.SPEEDTEST_RESULT }}
                draft: false
                prerelease: false